sonar.projectKey=cicd-tasklist-frontend
sonar.projectName=Task List Frontend
sonar.projectVersion=0.0.0

sonar.sources=src
sonar.exclusions=src/__tests__/**,src/main.tsx,src/vite-env.d.ts

sonar.tests=src/__tests__
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true


